[ups01]
    driver = "usbhid-ups"
    product = "CP1500PFCRM2U"
    desc = "Server Rack UPS"
    port = "auto"
    venderid = "0764"
    productid = "0601"
    serial = "BHWRT7005033"
    vendor = "CPS"
    bus = "001"
